In [118]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, normalize, MinMaxScaler

In [119]:
df = pd.DataFrame()
df['x'] = np.arange(5, 15)
df['y'] = np.arange(10, 20)
df

x   y
0   5  10
1   6  11
2   7  12
3   8  13
4   9  14
5  10  15
6  11  16
7  12  17
8  13  18
9  14  19

In [120]:
# StandardScaler: the input `x` must be 2D array
# reshape the 1D array to 2D array, or write 1D array as `[x]`
sc = StandardScaler()
x_2D = df['x'].to_numpy().reshape(-1, 1)
print(df['x'].shape)
print(x_2D.shape)
sc.fit(x_2D)
x_std = sc.transform(x_2D)
x_std

(10,)
(10, 1)


array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [121]:
# normalize: the input must be 2D array
norm = normalize([df['x']])
# x_2D = df['x'].to_numpy().reshape(1, -1)
# norm = normalize(x_2D)
norm

array([[0.15931325, 0.1911759 , 0.22303855, 0.2549012 , 0.28676384,
        0.31862649, 0.35048914, 0.38235179, 0.41421444, 0.44607709]])

In [122]:
# axis=1 by default. If axis=0, normalization happens along a column.
norm = normalize(df, axis=0)
df_norm = pd.DataFrame(norm, columns=df.columns)
df_norm

x         y
0  0.159313  0.213931
1  0.191176  0.235324
2  0.223039  0.256718
3  0.254901  0.278111
4  0.286764  0.299504
5  0.318626  0.320897
6  0.350489  0.342290
7  0.382352  0.363683
8  0.414214  0.385076
9  0.446077  0.406469

In [123]:
# MinMaxScaler
scaler = MinMaxScaler()
x_minmax = scaler.fit_transform(x_2D)
x_minmax

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])